apiVersion: apps/v1
kind: Deployment

metadata:
  name: my-redis

spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-redis
  template:
    metadata:
      labels:
        app: my-redis
    spec:
      containers:
      - name: my-redis
      image: redis
      volumeMounts:
      - name: redis-data
      mountPath: /data
      ports:
      - containerPort: 6379
      protocol: TCP
      volumes:
      - name: redis-data
      persistentVolumeClaim:
      claimName: conf-redis
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"